### ISSUE TITLE
I wrote an article in Chinese to introduce this app.

### ISSUE THREAD

**Issue by BlindingDark** [ming030890/Eng-Chi-Dictionary#14]
you can read it click [here](http://www.jianshu.com/p/cd414246bf5e)
我还是用中文吧，我英语太烂了。
我特别喜欢你这个应用。
哈哈，如果可以的话，你可以把我这篇文章放在README里面。

**Comment by tony-mak** [comment]
Thanks for writing up an article, much appreciated!
Apparently you are a developer as well.
Do you wanna maintain/update this project in the long term with me? Let's say have better simplified Chinese support? 
Let me know your opinion!

**Comment by BlindingDark** [comment]
My English is not very good, So I can't reply you immediately. sorry for that.
I wanna help you to maintain this project,
But I‘m afraid my ability is not enough.
I'm still in college.Just learning a short time in Android.
But,If I find another bug I can fixed ,I will fix it.
And I will provide support in simplified Chinese as I can.

Repeat in Chinese:
我英语不好见谅啊，
用英文写是觉得这里是国际社区，为了让更多人能看懂，就用蹩脚的英文写一遍了。
用中文再写一遍，就是怕我蹩脚的英语在表达上有偏差。
我水平比较菜，而且没有把你的代码全部读完，所以可能不能很好的帮助你。
如果有可能我会尽量支持你。
如果有可能的话，我们私聊的时候如果能使用中文的话那就太好了。
见谅啊。

**Comment by tony-mak** [comment]
中文當然沒問題，這是我的電郵，歡迎隨時找我
ming030890_at_gmail.com, 請將 _at_ 換成 @
哈哈，正在諗大學也沒有問題，當是興趣玩玩就可以了!
反而上班後就沒多時間搞這些了, 我也很久沒有更新了 :(
隨了fix bug 外，大概我們可以將想做的東西開記得 (issue), 有時間就可以實踐它們。
還有我加了你做collaborator, 你也可以直接更新這裡了。 

謝謝
